
import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class RecordedSimulation extends Simulation {
	val feeder = csv("search.csv").queue

	val httpProtocol = http
		.baseURL("https://guriensino.unipampa.edu.br")
		.inferHtmlResources()
		.acceptHeader("image/webp,image/apng,image/*,*/*;q=0.8")
		.userAgentHeader("Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36")

	val headers_0 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
		"Upgrade-Insecure-Requests" -> "1")

	val headers_1 = Map(
		"Accept" -> "text/css,*/*;q=0.1",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7")

	val headers_10 = Map(
		"Accept" -> "*/*",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7")

	val headers_32 = Map(
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7")

	val headers_56 = Map(
		"Accept" -> "*/*",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
		"Content-Type" -> "application/x-www-form-urlencoded; charset=UTF-8",
		"Origin" -> "https://guriensino.unipampa.edu.br",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_117 = Map(
		"Accept" -> "*/*",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_121 = Map(
		"Accept" -> "*/*",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
		"Origin" -> "https://guriensino.unipampa.edu.br",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_125 = Map(
		"Accept" -> "application/json",
		"Accept-Encoding" -> "gzip, deflate",
		"Accept-Language" -> "pt-BR",
		"Authorization" -> "Bearer x5ybbyiTyIp8YRShWAJfAIbujl0F9t8vzEMEBi5lz8Z5tYBky429DhPHTs83Yy0emqW6GMDpWyjrVPrL5ZU=",
		"Content-Type" -> "application/x-www-form-urlencoded",
		"User-Agent" -> "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) GitKraken/3.6.4 Chrome/59.0.3071.115 Electron/1.8.4 Safari/537.36")

	val headers_126 = Map(
		"Accept" -> "*/*",
		"Connection" -> "Keep-Alive",
		"Pragma" -> "no-cache",
		"User-Agent" -> "git/2.0 (libgit2 0.27.1)")

	val headers_127 = Map(
		"Accept" -> "*/*",
		"Authorization" -> "Basic eC10b2tlbi1hdXRoOng1eWJieWlUeUlwOFlSU2hXQUpmQUlidWpsMEY5dDh2ekVNRUJpNWx6OFo1dFlCa3k0MjlEaFBIVHM4M1l5MGVtcVc2R01EcFd5anJWUHJMNVpVPQ==",
		"Connection" -> "Keep-Alive",
		"Pragma" -> "no-cache",
		"User-Agent" -> "git/2.0 (libgit2 0.27.1)")

	val headers_390 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
		"Content-Type" -> "multipart/form-data; boundary=----WebKitFormBoundaryHYqGa3B3UFRgCsA7",
		"Origin" -> "https://guriensino.unipampa.edu.br",
		"Upgrade-Insecure-Requests" -> "1")

    val uri1 = "guriensino.unipampa.edu.br"
    val uri2 = "https://fonts.googleapis.com/css"
    val uri3 = "https://bitbucket.org:443/devpampateam/appagendeiquadra.git/info/refs"
    val uri4 = "https://api.bitbucket.org:443/2.0/repositories/devpampateam/appagendeiquadra"

	val scn = scenario("RecordedSimulation")
		.exec(http("request_0")
			.get("/guri/")
			.headers(headers_0)
			.resources(http("request_1")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_2")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_3")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_4")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_5")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_6")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_7")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_8")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_9")
			.get("/guri/application/modules/ptl//views/public/css/carrossel.css")
			.headers(headers_1),
            http("request_10")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_11")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_12")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_13")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_14")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_15")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_16")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_17")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_18")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_19")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_20")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_21")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_22")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_23")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_24")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_25")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_26")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_27")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_28")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_29")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_30")
			.get("/guri/application/modules/ptl//views/public/js/carrossel.js")
			.headers(headers_10),
            http("request_31")
			.get("/guri/application/modules/ptl//views/public/js/login.js")
			.headers(headers_10),
            http("request_32")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_33")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_34")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_35")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_36")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_37")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_38")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_39")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_40")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_41")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_42")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_43")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_44")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_45")
			.get("/guri/public/themes/moder/imgs/instrucoes.png")
			.headers(headers_32),
            http("request_46")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_47")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_48")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_49")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_50")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_51")
			.get("/guri/public/themes/moder//imgs/lock.png")
			.headers(headers_32),
            http("request_52")
			.get("/guri/public/themes/moder//imgs/novo_user.png")
			.headers(headers_32),
            http("request_53")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_54")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_55")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32)))
		.pause(9)
		.exec(http("request_56")
			.post("/guri/ptl/sistema/login")
			.headers(headers_56)
			.formParam("login", "161450029")
			.formParam("senha", "Hangar07051")
			.formParam("captcha", "")
			.resources(http("request_57")
			.get("/guri/ptl/sistema/principal")
			.headers(headers_0),
            http("request_58")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_59")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_60")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_61")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_62")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_63")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_64")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_65")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_66")
			.get("/guri/application/modules/ptl/views/public/css/carrossel.css")
			.headers(headers_1),
            http("request_67")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_68")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_69")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_70")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_71")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_72")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_73")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_74")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_75")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_76")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_77")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_78")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_79")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_80")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_81")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_82")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_83")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_84")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_85")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_86")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_87")
			.get("/guri/application/modules/ptl/views/public/js/carrossel.js")
			.headers(headers_10),
            http("request_88")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_89")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_90")
			.get("/guri/public/themes/moder/imgs/user.png")
			.headers(headers_32),
            http("request_91")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_92")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_93")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_94")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png")
			.headers(headers_32),
            http("request_95")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_96")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_97")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_98")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_99")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_100")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_101")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_102")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_103")
			.get("/guri/public/themes/moder/imgs/logo_guri.jpg")
			.headers(headers_32),
            http("request_104")
			.get("/guri/public/themes/moder/imgs/situacao_livro.png")
			.headers(headers_32),
            http("request_105")
			.get("/guri/public/themes/moder/imgs/painel_aluno_24.png")
			.headers(headers_32),
            http("request_106")
			.get("/guri/public/themes/moder/imgs/consultar_processo.png")
			.headers(headers_32),
            http("request_107")
			.get("/guri/public/themes/moder/imgs/inicial_restaurante.png")
			.headers(headers_32),
            http("request_108")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_109")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_110")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_111")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_112")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_113")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_114")
			.get("/guri/public/themes/moder//imgs/diagonals_5.png")
			.headers(headers_32),
            http("request_115")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_116")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32),
            http("request_117")
			.get("/guri/ptl/sistema/getDadosPesquisaAndifesAlunoAjax/03340361002")
			.headers(headers_117),
            http("request_118")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-soft_15_5f8168_1x100.png")
			.headers(headers_32),
            http("request_119")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_ffffff_256x240.png")
			.headers(headers_32),
            http("request_120")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_dots-small_65_bcbdbc_2x2.png")
			.headers(headers_32),
            http("request_121")
			.post("/guri/ptl/sistema/abrirDialogPesqAndifes/")
			.headers(headers_121),
            http("request_122")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-hard_100_eeeeee_1x100.png")
			.headers(headers_32)))
		.pause(1)
		.exec(http("request_123")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-hard_100_f6f6f6_1x100.png")
			.headers(headers_32)
			.resources(http("request_124")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_65_ffffff_40x100.png")
			.headers(headers_32)))
		.pause(7)
		.exec(http("request_125")
			.get(uri4 + "/pullrequests?state=OPEN")
			.headers(headers_125)
			.resources(http("request_126")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_126)
			.check(status.is(401)),
            http("request_127")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_127)
			.basicAuth("x-token-auth","x5ybbyiTyIp8YRShWAJfAIbujl0F9t8vzEMEBi5lz8Z5tYBky429DhPHTs83Yy0emqW6GMDpWyjrVPrL5ZU="),
            http("request_128")
			.get(uri4 + "?")
			.headers(headers_125)))
		.pause(5)
		.exec(http("request_129")
			.get("/guri/psa/processos/")
			.headers(headers_0)
			.resources(http("request_130")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_131")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_132")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_133")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_134")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_135")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_136")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_137")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_138")
			.get("/guri/application/modules/psa/views/public/css/processo.css")
			.headers(headers_1),
            http("request_139")
			.get("/guri/application/modules/psa/views/public/css/listagem.css")
			.headers(headers_1),
            http("request_140")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_141")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_142")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_143")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_144")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_145")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_146")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_147")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_148")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_149")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_150")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_151")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_152")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_153")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_154")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_155")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_156")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_157")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_158")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_159")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_160")
			.get("/guri/application/modules/psa/views/public/js/processo.js")
			.headers(headers_10),
            http("request_161")
			.get("/guri/application/modules/psa/views/public/js/listagem.js")
			.headers(headers_10),
            http("request_162")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_163")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_164")
			.get("/guri/public/themes/moder/imgs/user.png")
			.headers(headers_32),
            http("request_165")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_166")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_167")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_168")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png")
			.headers(headers_32),
            http("request_169")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_170")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_171")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_172")
			.get("/guri/public/themes/moder//imgs/home_32.png")
			.headers(headers_32),
            http("request_173")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_174")
			.get("/guri/public/themes/moder//imgs/seta_baixo_14.png")
			.headers(headers_32),
            http("request_175")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_176")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_177")
			.get("/guri/public/themes/moder/imgs/seta-direita.png")
			.headers(headers_32),
            http("request_178")
			.get("/guri/public/themes/moder//imgs/edit_user_32.png")
			.headers(headers_32),
            http("request_179")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_180")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_181")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_182")
			.get("/guri/public/themes/moder/imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_183")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_184")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_185")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_186")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_187")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_188")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_189")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32),
            http("request_190")
			.post("/guri/psa/processos/mostrarConcursosAnoAjax/")
			.headers(headers_56)
			.formParam("ano", "2018"),
            http("request_191")
			.get("/guri/public/themes/moder//imgs/seta_baixo_14.png")
			.headers(headers_32),
            http("request_192")
			.get("/guri/public/themes/moder/imgs/seta-direita.png")
			.headers(headers_32)))
		.pause(2)
		.exec(http("request_193")
			.get("/guri/psa/processos/visualizarProcessoSeletivo/concursosAbertos/7815")
			.headers(headers_0)
			.resources(http("request_194")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_195")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_196")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_197")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_198")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_199")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_200")
			.get("/guri/application/modules/psa/views/public/css/processo.css")
			.headers(headers_1),
            http("request_201")
			.get("/guri/application/modules/psa/views/public/css/listagem.css")
			.headers(headers_1),
            http("request_202")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_203")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_204")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_205")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_206")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_207")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_208")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_209")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_210")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_211")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_212")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_213")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_214")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_215")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_216")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_217")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_218")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_219")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_220")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_221")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_222")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_223")
			.get("/guri/application/modules/psa/views/public/js/listagem.js")
			.headers(headers_10),
            http("request_224")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_225")
			.get("/guri/application/modules/psa/views/public/js/processo.js")
			.headers(headers_10),
            http("request_226")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_227")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_228")
			.get("/guri/public/themes/moder/imgs/user.png")
			.headers(headers_32),
            http("request_229")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_230")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_231")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_232")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png")
			.headers(headers_32),
            http("request_233")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_234")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_235")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_236")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_237")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_238")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_239")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_240")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_241")
			.get("/guri/public/themes/moder//imgs/seta_voltar_32.png")
			.headers(headers_32),
            http("request_242")
			.get("/guri/public/themes/moder//imgs/edit_user_32.png")
			.headers(headers_32),
            http("request_243")
			.get("/guri/public/themes/moder//imgs/seta_direita_nova_16.png")
			.headers(headers_32),
            http("request_244")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_245")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_246")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_247")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_248")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_249")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_250")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_251")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32),
            http("request_252")
			.post("/guri/psa/processos/mostrarConcursosAnoAjax/")
			.headers(headers_56)
			.formParam("ano", "2018")))
		.pause(6)
		.exec(http("request_253")
			.get("/guri/psa/acesso/preInsc/3393/7815")
			.headers(headers_0)
			.resources(http("request_254")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_255")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_256")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_257")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_258")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_259")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_260")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_261")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_262")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_263")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_264")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_265")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_266")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_267")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_268")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_269")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_270")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_271")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_272")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_273")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_274")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_275")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_276")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_277")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_278")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_279")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_280")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_281")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_282")
			.get("/guri/application/modules/psa/views/public/js/processo.js")
			.headers(headers_10),
            http("request_283")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_284")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_285")
			.get("/guri/public/themes/moder/imgs/user.png")
			.headers(headers_32),
            http("request_286")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_287")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_288")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_289")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png")
			.headers(headers_32),
            http("request_290")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_291")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_292")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_293")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_294")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_295")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_296")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_297")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_298")
			.get("/guri/public/themes/moder//imgs/seta_voltar_32.png")
			.headers(headers_32),
            http("request_299")
			.get("/guri/public/themes/moder//imgs/ok_16.png")
			.headers(headers_32),
            http("request_300")
			.get("/guri/public/themes/moder//imgs/arrow_menu_16.png")
			.headers(headers_32),
            http("request_301")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_302")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_303")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_304")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_305")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_306")
			.get("/guri/public/themes/moder//imgs/arrow_menu_16.png")
			.headers(headers_32),
            http("request_307")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_308")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_309")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32)))
		.pause(3)
		.exec(http("request_310")
			.get("/guri/psa/candidato/novo")
			.headers(headers_0)
			.resources(http("request_311")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_312")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_313")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_314")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_315")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_316")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_317")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_318")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_319")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_320")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_321")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_322")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_323")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_324")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_325")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_326")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_327")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_328")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_329")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_330")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_331")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_332")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_333")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_334")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_335")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_336")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_337")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_338")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_339")
			.get("/guri/application/modules/psa/views/public/js/processo.js")
			.headers(headers_10),
            http("request_340")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_341")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_342")
			.get("/guri/public/themes/moder/imgs/user.png")
			.headers(headers_32),
            http("request_343")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_344")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_345")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_346")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png")
			.headers(headers_32),
            http("request_347")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_348")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_349")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_350")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_351")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_352")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_353")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_354")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_355")
			.get("/guri/public/themes/moder//imgs/ajax-loader-preto.gif")
			.headers(headers_32),
            http("request_356")
			.get("/guri/public/themes/moder//imgs/seta_voltar_32.png")
			.headers(headers_32),
            http("request_357")
			.get("/guri/public/themes/moder//imgs/salvar_32.png")
			.headers(headers_32),
            http("request_358")
			.get("/guri/public/themes/moder//imgs/cancel_32.png")
			.headers(headers_32),
            http("request_359")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_360")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_361")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_362")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_363")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_364")
			.get("/guri/public/themes/moder//imgs/ajax-loader-preto.gif")
			.headers(headers_32),
            http("request_365")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_366")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_367")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32)))
		.pause(12)
		.exec(http("request_368")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-hard_100_eeeeee_1x100.png")
			.headers(headers_32)
			.resources(http("request_369")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_glass_55_fbf8ee_1x400.png")
			.headers(headers_32),
            http("request_370")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-soft_15_5f8168_1x100.png")
			.headers(headers_32),
            http("request_371")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_ffffff_256x240.png")
			.headers(headers_32)))
		.pause(1)
		.exec(http("request_372")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_65_ffffff_40x100.png")
			.headers(headers_32))
		.pause(20)
		.exec(http("request_373")
			.get(uri4 + "/pullrequests?state=OPEN")
			.headers(headers_125)
			.resources(http("request_374")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_126)
			.check(status.is(401)),
            http("request_375")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_127)
			.basicAuth("x-token-auth","x5ybbyiTyIp8YRShWAJfAIbujl0F9t8vzEMEBi5lz8Z5tYBky429DhPHTs83Yy0emqW6GMDpWyjrVPrL5ZU="),
            http("request_376")
			.get(uri4 + "?")
			.headers(headers_125)))
		.pause(53)
		.exec(http("request_377")
			.post("/guri/psa/candidato/carregaMunicipiosAjax/")
			.headers(headers_56)
			.formParam("sigla", "RS        "))
		.pause(3)
		.exec(http("request_378")
			.get(uri4 + "/pullrequests?state=OPEN")
			.headers(headers_125))
		.pause(1)
		.exec(http("request_379")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_126)
			.resources(http("request_380")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_127)
			.basicAuth("x-token-auth","x5ybbyiTyIp8YRShWAJfAIbujl0F9t8vzEMEBi5lz8Z5tYBky429DhPHTs83Yy0emqW6GMDpWyjrVPrL5ZU="),
            http("request_381")
			.get(uri4 + "?")
			.headers(headers_125))
			.check(status.is(401)))
		.pause(4)
		.exec(http("request_382")
			.post("/guri/psa/candidato/carregaMunicipiosAjax/")
			.headers(headers_56)
			.formParam("sigla", "RS        "))
		.pause(53)
		.exec(http("request_383")
			.get(uri4 + "/pullrequests?state=OPEN")
			.headers(headers_125)
			.resources(http("request_384")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_126)
			.check(status.is(401)),
            http("request_385")
			.get(uri3 + "?service=git-upload-pack")
			.headers(headers_127)
			.basicAuth("x-token-auth","x5ybbyiTyIp8YRShWAJfAIbujl0F9t8vzEMEBi5lz8Z5tYBky429DhPHTs83Yy0emqW6GMDpWyjrVPrL5ZU="),
            http("request_386")
			.get(uri4 + "?")
			.headers(headers_125)))
		.pause(23)
		.feed(feeder)
		.exec(http("request_387")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_dots-small_65_bcbdbc_2x2.png")
			.headers(headers_32)
			.resources(http("request_388")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-hard_100_f6f6f6_1x100.png")
			.headers(headers_32),
            http("request_389")
			.post("/guri/ptl/sistema/isLogado")
			.headers(headers_121),
            http("request_390")
			.post("/guri/psa/candidato/salvar")
			.headers(headers_390)
			.body(ElFileBody ("RecordedSimulation_0390_request.txt")),
            http("request_391")
			.get("/guri/psa/inscricao/novo")
			.headers(headers_0),
            http("request_392")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_393")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_394")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_395")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_396")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_397")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_398")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_399")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_400")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_401")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_402")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_403")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_404")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_405")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_406")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_407")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_408")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_409")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_410")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_411")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_412")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_413")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_414")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_415")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_416")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_417")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_418")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_419")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_420")
			.get("/guri/application/modules/psa/views/public/js/inscricao.js")
			.headers(headers_10),
            http("request_421")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_422")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_423")
			.get("/guri/public/themes/moder/imgs/user.png")
			.headers(headers_32),
            http("request_424")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_425")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_426")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_427")
			.get("/guri/application/modules/pta/views/public/imgs/aluno_16.png")
			.headers(headers_32),
            http("request_428")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_429")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_430")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_431")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_432")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_433")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_434")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_435")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_436")
			.get("/guri/public/themes/moder//imgs/seta_voltar_32.png")
			.headers(headers_32),
            http("request_437")
			.get("/guri/public/themes/moder//imgs/salvar_32.png")
			.headers(headers_32),
            http("request_438")
			.get("/guri/public/themes/moder//imgs/cancel_32.png")
			.headers(headers_32),
            http("request_439")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_440")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_441")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_442")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_443")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_444")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_445")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_446")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32),
            http("request_447")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_highlight-soft_15_5f8168_1x100.png")
			.headers(headers_32),
            http("request_448")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_ffffff_256x240.png")
			.headers(headers_32)))
		.pause(6)
		.exec(http("request_449")
			.get("/guri/ptl/sistema/logout")
			.headers(headers_0)
			.resources(http("request_450")
			.get("/guri/public/themes/moder//css/estilo_menu.css")
			.headers(headers_1),
            http("request_451")
			.get("/guri/public/themes/moder//css/tabs.css")
			.headers(headers_1),
            http("request_452")
			.get("/guri/public/themes/moder//css/estilo_admin.css")
			.headers(headers_1),
            http("request_453")
			.get("/guri/public/themes/moder//css/dd.css")
			.headers(headers_1),
            http("request_454")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/jquery-ui-1.8.18.custom.css")
			.headers(headers_1),
            http("request_455")
			.get("/guri/public/themes/moder//css/select2.min.css")
			.headers(headers_1),
            http("request_456")
			.get("/guri/public/themes/moder//css/nav_etapas.css")
			.headers(headers_1),
            http("request_457")
			.get("/guri/public/themes/moder//css/form_2018.css")
			.headers(headers_1),
            http("request_458")
			.get("/guri/application/modules/ptl/views/public/css/carrossel.css")
			.headers(headers_1),
            http("request_459")
			.get("/guri/public/js/jquery.price_format.1.0.js")
			.headers(headers_10),
            http("request_460")
			.get("/guri/public/js/jquery.maskedinput-1.3.1.min.js")
			.headers(headers_10),
            http("request_461")
			.get("/guri/public/js/jquery.upload-1.0.2.min.js")
			.headers(headers_10),
            http("request_462")
			.get("/guri/public/js/angular.min.js")
			.headers(headers_10),
            http("request_463")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-ui-1.9.0.custom.min.js")
			.headers(headers_10),
            http("request_464")
			.get("/guri/public/js/jquery-ui-1.9.0/js/jquery-1.8.2.js")
			.headers(headers_10),
            http("request_465")
			.get("/guri/public/js/jquery.cookie.js")
			.headers(headers_10),
            http("request_466")
			.get("/guri/public/js/jquery.dd.js")
			.headers(headers_10),
            http("request_467")
			.get("/guri/public/js/jquery.multifile.js")
			.headers(headers_10),
            http("request_468")
			.get("/guri/public/js/acessivel.js")
			.headers(headers_10),
            http("request_469")
			.get("/guri/public/js/dialog_sessao.js")
			.headers(headers_10),
            http("request_470")
			.get("/guri/public/js/admin.js")
			.headers(headers_10),
            http("request_471")
			.get("/guri/public/js/validacoes.js")
			.headers(headers_10),
            http("request_472")
			.get("/guri/public/js/tabs.js")
			.headers(headers_10),
            http("request_473")
			.get("/guri/public/js/tabs.min.js")
			.headers(headers_10),
            http("request_474")
			.get("/guri/public/js/select2/js/i18n/pt-BR.js")
			.headers(headers_10),
            http("request_475")
			.get("/guri/public/js/jquery-i18n/jquery.i18n.min.js")
			.headers(headers_10),
            http("request_476")
			.get("/guri/public/js/jquery-i18n/dicionario.js")
			.headers(headers_10),
            http("request_477")
			.get("/guri/public/js/jquery-i18n/tradutor.js")
			.headers(headers_10),
            http("request_478")
			.get("/guri/public/js/select2/js/select2.min.js")
			.headers(headers_10),
            http("request_479")
			.get("/guri/application/modules/ptl/views/public/js/carrossel.js")
			.headers(headers_10),
            http("request_480")
			.get("/guri/application/modules/ptl/views/public/js/login.js")
			.headers(headers_10),
            http("request_481")
			.get("/guri/public/themes/moder/imgs/marca.png")
			.headers(headers_32),
            http("request_482")
			.get("/guri/public/themes/moder/imgs/logo_guri.png")
			.headers(headers_32),
            http("request_483")
			.get("/guri/public/themes/moder/imgs/login.png")
			.headers(headers_32),
            http("request_484")
			.get("/guri/public/themes/moder/imgs/contraste.png")
			.headers(headers_32),
            http("request_485")
			.get("/guri/public/themes/moder/imgs/mapa-site.png")
			.headers(headers_32),
            http("request_486")
			.get("/guri/application/modules/psa/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_487")
			.get("/guri/public/themes/moder//imgs/help_vermelho.png")
			.headers(headers_32),
            http("request_488")
			.get("/guri/application/modules/pss/views/public/imgs/icone_psa_16.png")
			.headers(headers_32),
            http("request_489")
			.get("/guri/application/modules/evt/views/public/imgs/meeting_16.png")
			.headers(headers_32),
            http("request_490")
			.get("/guri/application/modules/ptl/views/public/imgs/cubos_16.png")
			.headers(headers_32),
            http("request_491")
			.get("/guri/application/modules/man/views/public/imgs/help_verde.png")
			.headers(headers_32),
            http("request_492")
			.get("/guri/application/modules/rpt/views/public/imgs/report_16.png")
			.headers(headers_32),
            http("request_493")
			.get("/guri/public/themes/moder//imgs/ajax-loader-branco.gif")
			.headers(headers_32),
            http("request_494")
			.get("/guri/public/themes/moder/imgs/instrucoes.png")
			.headers(headers_32),
            http("request_495")
			.get("/guri/public/themes/moder//imgs/ajax-loader-big.gif")
			.headers(headers_32),
            http("request_496")
			.get("/guri/public/themes/moder//imgs/help_verde.png")
			.headers(headers_32),
            http("request_497")
			.get("/guri/public/themes/moder//imgs/valid-xhtml10-blue.png")
			.headers(headers_32),
            http("request_498")
			.get("/guri/public/themes/moder//imgs/busca.png")
			.headers(headers_32),
            http("request_499")
			.get("/guri/public/themes/moder//imgs/marcador-lista.png")
			.headers(headers_32),
            http("request_500")
			.get("/guri/public/themes/moder//imgs/diagonals_3.png")
			.headers(headers_32),
            http("request_501")
			.get("/guri/public/themes/moder//imgs/lock.png")
			.headers(headers_32),
            http("request_502")
			.get("/guri/public/themes/moder//imgs/novo_user.png")
			.headers(headers_32),
            http("request_503")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-bg_flat_75_ffffff_40x100.png")
			.headers(headers_32),
            http("request_504")
			.get("/guri/public/js/jquery-ui-1.9.0/css/custom-theme/images/ui-icons_cc0000_256x240.png")
			.headers(headers_32)))
	setUp(scn.inject(atOnceUsers(500))).protocols(httpProtocol)
}